name: GitHub Actions Demo

on:
   workflow_dispatch:

jobs:
  hello: 
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: show
        run: echo hyy Tirth

